songs-app/config/routes.rb
Rails.application.routes.draw do
  get 'albums/index'
  resources :albums
  root 'artists#index'
  get 'songs/index'
  resources :songs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artists

end

songs-app/app/models/album.rb
class Album < ApplicationRecord
    has_many :songs
end

songs-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

songs-app/app/models/artist.rb
class Artist < ApplicationRecord
end

songs-app/app/models/song.rb
class Song < ApplicationRecord
    belongs_to :album
end

songs-app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all 
end

  def show
    @album = Album.find(params[:id])
  end
end

songs-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

songs-app/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @Artists = Artist.all
  end

  def show
    @Artist = Artist.find(params[:id])
  end
end

songs-app/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs= Song.all
  end
end

songs-app/app/helpers/albums_helper.rb
module AlbumsHelper
end

songs-app/app/helpers/application_helper.rb
module ApplicationHelper
end

songs-app/app/helpers/artists_helper.rb
module ArtistsHelper
end

songs-app/app/helpers/songs_helper.rb
module SongsHelper
end

songs-app/app/views/albums/create.html.erb
<h1>Albums#create</h1>
<p>Find me in app/views/albums/create.html.erb</p>

songs-app/app/views/albums/edit.html.erb
<h1>Albums#edit</h1>
<p>Find me in app/views/albums/edit.html.erb</p>

songs-app/app/views/albums/index.html.erb
<div class= "albums">
<% @albums.each do |album| %>
<div class="row">
  <div class="col">
    <div class="card" style="width: 18rem;">
        <img src="<%=album.image%>" class="card-img-top" alt="...">
            <div class="card-body">
                <a href="<%= album_path(album) %>"><%= album.name %></a>
            </div>
        </div>
    </div>
</div>
<%#= image_tag album.image %>
<% end %> 
</div>
  

songs-app/app/views/albums/new.html.erb
<h1>Albums#new</h1>
<p>Find me in app/views/albums/new.html.erb</p>

songs-app/app/views/albums/show.html.erb
<img src="<%=@album.image%>" alt="">
<p><strong>Album Name:</strong><%= @album.name %></p>
<p>album artist</p> 
<p>songs player </p>

<%= @album.id %>

songs-app/app/views/albums/update.html.erb
<h1>Albums#update</h1>
<p>Find me in app/views/albums/update.html.erb</p>

songs-app/app/views/artists/index.html.erb
<h2> Favourite Artists </h2>

    <%  @Artists.each do |artist| %>
   
<div class="card mr-5 ml-5 mb-3 mt-3   p-2" >

<%= link_to artist.name, artist_path(artist)%>


</div>


<% end %>

songs-app/app/views/artists/show.html.erb
<h2> Artists </h2>

<p>
<%= @Artist.name %>
</p>

<div class="card mr-5 ml-5 mb-3 mt-3   p-2" >

   

</div>

songs-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SongsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href=<%= artists_path %>>Artists</a>
            <a class="nav-item nav-link" href="<%= albums_index_path %>">Albums</a>
      <a class="nav-item nav-link" href=<%= songs_index_path %>>Songs</a>

    </div>
    </nav>
    <%= yield %>
  </body>
</html>

songs-app/app/views/songs/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Player</th>
      <th scope="col">Album Cover</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @songs.each do |song| %>
    <tr class= "song-card" scope="row">
        <td><%= song.name %></td>
        <td>        
            <audio controls>
                <source src="<%= song.link %>" type="audio/mpeg">
                Your browser does not support the audio element.
            </audio>
        </td>
        <td><img src="<%=song.cover %>" alt=""></td>
        <td><%= link_to 'View Album', album_path(song.album_id) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<!--<div class= "list">
    <strong>Name</strong>
    <strong>Player</strong>
    <strong>Album Cover</strong>
    <strong>Action</strong>
</div>

<% @songs.each do |song| %>
    <div class= "song-card">
        <p><%= song.name %></p>
        <audio controls>
            <source src="<%= song.link %>" type="audio/mpeg">
            Your browser does not support the audio element.
        </audio>
        <img src="<%=song.cover %>" alt="">
        <%= link_to 'View Album', album_path(song.album_id) %>
    </div>
    <br>
<% end %>-->